global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Tu microservicio en Railway
  - job_name: node
    metrics_path: "/metrics"
    scheme: "https"
    static_configs:
      - targets:
          - "microservicio-notificacionespush-production.up.railway.app"


